# Generated by Django 6.0 on 2025-12-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pending_tutor', 'Pending Tutor Approval'), ('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending_tutor', max_length=20),
        ),
    ]
